"""Validated canonical chess-position identity services."""

from .canonicalization import (
    CanonicalPosition,
    PositionValidationError,
    canonicalize_board,
    canonicalize_fen,
)
from .insight import (
    AnalysisState,
    PreferenceKind,
    PositionInsight,
    PositionInsightAnalysis,
    PositionInsightError,
    PositionInsightExperience,
    PositionInsightOpening,
    PositionInsightObservedMove,
    PositionInsightPreference,
    PositionInsightRepository,
    PositionInsightRequest,
    PositionInsightResult,
    PositionInsightSchemaError,
    PositionInsightStorageError,
    PositionInsightValidationError,
    TrainerColor,
    get_position_insight,
    read_position_insight,
)
from .repository import PositionRepository, PositionStorageError, position_transaction

__all__ = [
    "CanonicalPosition",
    "AnalysisState",
    "PreferenceKind",
    "PositionInsight",
    "PositionInsightAnalysis",
    "PositionInsightError",
    "PositionInsightExperience",
    "PositionInsightOpening",
    "PositionInsightObservedMove",
    "PositionInsightPreference",
    "PositionInsightRepository",
    "PositionInsightRequest",
    "PositionInsightResult",
    "PositionInsightSchemaError",
    "PositionInsightStorageError",
    "PositionInsightValidationError",
    "PositionValidationError",
    "PositionRepository",
    "PositionStorageError",
    "canonicalize_board",
    "canonicalize_fen",
    "get_position_insight",
    "position_transaction",
    "read_position_insight",
    "TrainerColor",
]
