from __future__ import annotations

import os
import sqlite3
import subprocess
import sys
from pathlib import Path

import pytest

from chess_move_trainer.database.inspection import inspect_schema, render_schema_markdown
from chess_move_trainer.database.publication import publish_schema

ROOT = Path(__file__).parents[2]


def _make_arbitrary_database(path: Path) -> None:
    with sqlite3.connect(path) as connection:
        connection.execute("PRAGMA user_version = 27")
        connection.executescript(
            """
            PRAGMA foreign_keys = ON;
            CREATE TABLE custom_parent (
                parent_id INTEGER PRIMARY KEY,
                label TEXT NOT NULL DEFAULT 'ordinary',
                UNIQUE(label)
            );
            CREATE TABLE custom_child (
                child_id INTEGER PRIMARY KEY,
                parent_id INTEGER NOT NULL,
                secret TEXT,
                FOREIGN KEY (parent_id) REFERENCES custom_parent(parent_id)
                    ON UPDATE CASCADE ON DELETE SET NULL
            );
            CREATE INDEX child_parent_index ON custom_child(parent_id);
            CREATE VIEW custom_view AS
                SELECT child_id, parent_id FROM custom_child;
            CREATE TRIGGER custom_trigger AFTER INSERT ON custom_child
            BEGIN
                UPDATE custom_parent SET label = label WHERE parent_id = NEW.parent_id;
            END;
            INSERT INTO custom_parent(parent_id, label) VALUES (1, 'ordinary');
            INSERT INTO custom_child(child_id, parent_id, secret)
                VALUES (2, 1, 'do-not-publish-this-row');
            """
        )


def _make_generated_column_database(path: Path) -> None:
    with sqlite3.connect(path) as connection:
        connection.executescript(
            """
            CREATE TABLE generated_values (
                base INTEGER NOT NULL,
                virtual_total INTEGER GENERATED ALWAYS AS (base + 1) VIRTUAL,
                stored_total INTEGER GENERATED ALWAYS AS (base + 2) STORED
            );
            """
        )


def _run_inspect_cli(database_path: Path, *extra: str) -> subprocess.CompletedProcess[bytes]:
    environment = os.environ.copy()
    environment.pop("PYTHONPATH", None)
    return subprocess.run(
        [
            sys.executable,
            "-m",
            "chess_move_trainer.database",
            "schema",
            "inspect",
            "--database",
            str(database_path),
            *extra,
        ],
        cwd=ROOT,
        env=environment,
        capture_output=True,
        timeout=15,
    )


def test_inspection_is_generic_and_includes_useful_metadata_without_rows_or_paths(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "arbitrary.db"
    _make_arbitrary_database(database_path)

    markdown = render_schema_markdown(inspect_schema(database_path)).decode("utf-8")

    assert "> Generated by `python -m chess_move_trainer.database schema inspect`;" in markdown
    assert "user_version" in markdown
    assert "27" in markdown
    assert "custom_parent" in markdown
    assert "custom_child" in markdown
    assert "parent_id" in markdown
    assert "NOT NULL" in markdown
    assert "ordinary" in markdown
    assert "custom_parent" in markdown and "custom_view" in markdown
    assert "custom_trigger" in markdown
    assert "child_parent_index" in markdown
    assert "sqlite_autoindex_custom_parent" in markdown
    assert "ON UPDATE CASCADE" in markdown
    assert "ON DELETE SET NULL" in markdown
    assert "CREATE TABLE custom_child" in markdown
    assert "CREATE VIEW custom_view" in markdown
    assert "CREATE TRIGGER custom_trigger" in markdown
    assert "do-not-publish-this-row" not in markdown
    assert str(database_path) not in markdown
    assert "Generated at" not in markdown


def test_inspection_includes_generated_columns_and_their_sqlite_kinds(tmp_path: Path) -> None:
    database_path = tmp_path / "generated-columns.db"
    _make_generated_column_database(database_path)

    inspection = inspect_schema(database_path)
    table = next(table for table in inspection.tables if table.name == "generated_values")
    kinds = {column.name: column.kind for column in table.columns}
    markdown = render_schema_markdown(inspection).decode("utf-8")

    assert kinds == {
        "base": "normal",
        "virtual_total": "virtual-generated",
        "stored_total": "stored-generated",
    }
    assert "| Kind |" in markdown
    assert "virtual-generated" in markdown
    assert "stored-generated" in markdown


def test_inspection_missing_database_is_read_only_and_never_creates_target(tmp_path: Path) -> None:
    database_path = tmp_path / "missing.db"

    with pytest.raises(FileNotFoundError):
        inspect_schema(database_path)

    assert not database_path.exists()


def test_inspection_preserves_input_bytes_and_is_deterministic(tmp_path: Path) -> None:
    database_path = tmp_path / "repeatable.db"
    _make_arbitrary_database(database_path)
    original_bytes = database_path.read_bytes()

    first = render_schema_markdown(inspect_schema(database_path))
    second = render_schema_markdown(inspect_schema(database_path))

    assert first == second
    assert database_path.read_bytes() == original_bytes


def test_inspect_cli_emits_markdown_to_stdout(tmp_path: Path) -> None:
    database_path = tmp_path / "stdout.db"
    _make_arbitrary_database(database_path)

    result = _run_inspect_cli(database_path)

    assert result.returncode == 0
    assert result.stdout.startswith(b"# SQLite schema reference")
    assert b"custom_child" in result.stdout
    assert result.stderr == b""


def test_inspect_cli_output_matches_stdout_bytes(tmp_path: Path) -> None:
    database_path = tmp_path / "stdout-and-file.db"
    output_path = tmp_path / "schema.md"
    _make_arbitrary_database(database_path)

    result = _run_inspect_cli(database_path, "--output", str(output_path))

    assert result.returncode == 0
    assert output_path.read_bytes() == result.stdout
    assert result.stderr == b""


def test_atomic_publication_writes_identical_bytes_from_destination_directory(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    database_path = tmp_path / "database.db"
    output_path = tmp_path / "published" / "schema.md"
    output_path.parent.mkdir()
    _make_arbitrary_database(database_path)
    replacements: list[tuple[Path, Path]] = []
    original_replace = os.replace

    def record_replace(
        source: str | bytes | os.PathLike[str],
        destination: str | bytes | os.PathLike[str],
    ) -> None:
        source_path = Path(source)
        destination_path = Path(destination)
        replacements.append((source_path, destination_path))
        original_replace(source, destination)

    monkeypatch.setattr("chess_move_trainer.database.publication.os.replace", record_replace)

    published = publish_schema(database_path, output_path)

    assert output_path.read_bytes() == published
    assert replacements == [(replacements[0][0], output_path)]
    assert replacements[0][0].parent == output_path.parent
    assert replacements[0][0] != output_path


def test_existing_output_survives_inspection_render_and_write_failures(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    database_path = tmp_path / "database.db"
    output_path = tmp_path / "schema.md"
    _make_arbitrary_database(database_path)
    original_output = b"keep this reference"
    output_path.write_bytes(original_output)

    monkeypatch.setattr(
        "chess_move_trainer.database.publication.render_schema_markdown",
        lambda inspection: (_ for _ in ()).throw(RuntimeError("render failed")),
    )
    with pytest.raises(RuntimeError, match="render failed"):
        publish_schema(database_path, output_path)
    assert output_path.read_bytes() == original_output

    monkeypatch.undo()

    def fail_replace(source: object, destination: object) -> None:
        raise OSError("write failed")

    monkeypatch.setattr("chess_move_trainer.database.publication.os.replace", fail_replace)
    with pytest.raises(OSError, match="write failed"):
        publish_schema(database_path, output_path)
    assert output_path.read_bytes() == original_output

    malformed_database = tmp_path / "malformed.db"
    malformed_database.write_bytes(b"not a sqlite database")
    with pytest.raises(Exception):
        publish_schema(malformed_database, output_path)
    assert output_path.read_bytes() == original_output


def test_output_database_collision_is_rejected_without_damage(tmp_path: Path) -> None:
    database_path = tmp_path / "database.db"
    _make_arbitrary_database(database_path)
    original_bytes = database_path.read_bytes()
    alias_path = tmp_path / "database-alias.db"
    os.link(database_path, alias_path)

    with pytest.raises(ValueError, match="selected database"):
        publish_schema(database_path, alias_path)

    assert database_path.read_bytes() == original_bytes
    assert alias_path.read_bytes() == original_bytes


def test_output_parent_must_exist_and_existing_output_is_untouched(tmp_path: Path) -> None:
    database_path = tmp_path / "database.db"
    _make_arbitrary_database(database_path)
    output_path = tmp_path / "missing" / "schema.md"

    with pytest.raises(FileNotFoundError):
        publish_schema(database_path, output_path)

    assert not output_path.parent.exists()
