from __future__ import annotations

from pathlib import Path

from chess_move_trainer.database.inspection import inspect_schema, render_schema_markdown
from chess_move_trainer.database.schema import create_schema

ROOT = Path(__file__).parents[2]
REFERENCE_PATH = ROOT / "data" / "database" / "schema.md"


def test_committed_reference_matches_a_fresh_canonical_database(tmp_path: Path) -> None:
    database_path = tmp_path / "fresh-v1.db"
    create_schema(database_path)

    generated = render_schema_markdown(inspect_schema(database_path))

    assert REFERENCE_PATH.read_bytes() == generated
    reference_text = generated.decode("utf-8")
    marker = "> Generated by `python -m chess_move_trainer.database schema inspect`;"
    assert marker in reference_text
    assert "do not edit" in reference_text.lower()
    assert all(term not in reference_text.lower() for term in ("new", "replacement", "rebuilt"))
