from __future__ import annotations

from pathlib import Path

from chess_move_trainer.database.inspection import inspect_schema, render_schema_markdown
from chess_move_trainer.database.schema import create_schema


ROOT = Path(__file__).parents[2]
REFERENCE_PATH = ROOT / "data" / "database" / "schema.md"
LEGACY_REFERENCE_PATH = ROOT / "data" / "database" / "schema.txt"


def test_committed_reference_matches_a_fresh_canonical_database(tmp_path: Path) -> None:
    database_path = tmp_path / "fresh-v1.db"
    create_schema(database_path)

    generated = render_schema_markdown(inspect_schema(database_path))

    assert REFERENCE_PATH.read_bytes() == generated
    reference_text = generated.decode("utf-8")
    assert "> Generated by `python -m chess_move_trainer.database schema inspect`;" in reference_text
    assert "do not edit" in reference_text.lower()
    assert all(term not in reference_text.lower() for term in ("new", "replacement", "rebuilt"))


def test_schema_router_links_new_reference_separately_and_preserves_legacy_link() -> None:
    router = (ROOT / "docs" / "README.md").read_text(encoding="utf-8")

    assert "../data/database/schema.md" in router
    assert "../data/database/schema.txt" in router
    assert "schema.md" in router and "schema.txt" in router
    assert LEGACY_REFERENCE_PATH.is_file()
