"""Offline persistence for the authorized opening source catalog."""

from .classification import (
    AnchorFact,
    ClassificationAnchorFact,
    ClassificationError,
    ClassificationFacts,
    ClassificationGameFact,
    ClassificationRouteFact,
    GameFact,
    RouteFact,
    derive_classification,
    derive_classifications,
)
from .classification_contract import (
    AnchorIdentity,
    CatalogIdentity,
    GameOccurrenceIdentity,
    PositionKey,
    exact_endpoint_match,
    suffix_plies,
    validate_route_plies,
)
from .classification_persistence import (
    ClassificationImportResult,
    ClassificationPublicationError,
    import_classification,
    import_classifications,
    publish_classification,
    publish_classifications,
)
from .classification_schema import (
    CLASSIFICATION_SCHEMA_VERSION,
    ensure_classification_schema,
)
from .importer import (
    EXPECTED_SOURCE_FILES,
    SOURCE_DATASET,
    ImportResult,
    OpeningCatalogError,
    OpeningReplayError,
    OpeningSourceChangedError,
    canonical_row_hash,
    import_catalog,
    load_source,
)
from .relationship_persistence import import_relationships, publish_relationships
from .relationships import (
    MembershipFact,
    ParentFact,
    RelationshipFacts,
    RelationshipImportResult,
    TranspositionFact,
    derive_relationships,
)
from .schema import (
    RELATIONSHIP_SCHEMA_VERSION,
    SCHEMA_VERSION,
    OpeningSchemaError,
    ensure_relationship_schema,
    ensure_schema,
)

__all__ = [
    "EXPECTED_SOURCE_FILES",
    "SOURCE_DATASET",
    "SCHEMA_VERSION",
    "RELATIONSHIP_SCHEMA_VERSION",
    "CLASSIFICATION_SCHEMA_VERSION",
    "ImportResult",
    "OpeningCatalogError",
    "OpeningReplayError",
    "OpeningSchemaError",
    "OpeningSourceChangedError",
    "canonical_row_hash",
    "ensure_schema",
    "import_catalog",
    "load_source",
    "MembershipFact",
    "ParentFact",
    "RelationshipFacts",
    "RelationshipImportResult",
    "TranspositionFact",
    "derive_relationships",
    "ensure_relationship_schema",
    "import_relationships",
    "publish_relationships",
    "AnchorIdentity",
    "CatalogIdentity",
    "GameOccurrenceIdentity",
    "PositionKey",
    "exact_endpoint_match",
    "suffix_plies",
    "validate_route_plies",
    "ensure_classification_schema",
    "ClassificationAnchorFact",
    "ClassificationError",
    "ClassificationFacts",
    "ClassificationGameFact",
    "ClassificationImportResult",
    "ClassificationPublicationError",
    "ClassificationRouteFact",
    "AnchorFact",
    "GameFact",
    "RouteFact",
    "derive_classification",
    "derive_classifications",
    "import_classification",
    "import_classifications",
    "publish_classification",
    "publish_classifications",
]
