"""Generic, read-only SQLite metadata inspection and Markdown rendering."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from sqlalchemy.engine import Connection

from .connection import (
    DEFAULT_LOCK_TIMEOUT_SECONDS,
    _open_connection,
    _validate_database_path,
    _validate_lock_timeout,
)


@dataclass(frozen=True)
class SchemaObject:
    """One object recorded by SQLite's schema catalogue."""

    object_type: str
    name: str
    table_name: str | None
    sql: str | None


@dataclass(frozen=True)
class SchemaColumn:
    """One column returned by SQLite table metadata."""

    ordinal: int
    name: str
    declared_type: str
    not_null: bool
    default_value: str | None
    primary_key_order: int
    kind: str


@dataclass(frozen=True)
class SchemaForeignKey:
    """One column mapping in a SQLite foreign-key constraint."""

    constraint_id: int
    sequence: int
    referenced_table: str
    from_column: str
    to_column: str | None
    on_update: str
    on_delete: str
    match: str


@dataclass(frozen=True)
class SchemaIndex:
    """One table index, including SQLite internal constraint indexes."""

    name: str
    table_name: str
    unique: bool
    origin: str
    partial: bool
    columns: tuple[str | None, ...]
    sql: str | None


@dataclass(frozen=True)
class SchemaTable:
    """A table and its generic column and foreign-key metadata."""

    name: str
    columns: tuple[SchemaColumn, ...]
    foreign_keys: tuple[SchemaForeignKey, ...]
    sql: str | None


@dataclass(frozen=True)
class SchemaInspection:
    """Ordinary data describing one read-only SQLite schema inspection."""

    user_version: int
    objects: tuple[SchemaObject, ...]
    tables: tuple[SchemaTable, ...]
    indexes: tuple[SchemaIndex, ...]


_OBJECT_TYPE_ORDER = {"table": 0, "index": 1, "trigger": 2, "view": 3}
_COLUMN_KIND_BY_XINFO_CODE = {
    0: "normal",
    1: "hidden virtual-table",
    2: "virtual-generated",
    3: "stored-generated",
}


def inspect_schema(
    database_path: str | Path,
    *,
    lock_timeout: float = DEFAULT_LOCK_TIMEOUT_SECONDS,
) -> SchemaInspection:
    """Read generic SQLite metadata without creating or changing the database."""

    path = _validate_database_path(database_path, "read-only")
    timeout_seconds = _validate_lock_timeout(lock_timeout)

    with _open_connection(path, "read-only", timeout_seconds) as connection:
        return _inspect_connection(connection)


def render_schema_markdown(inspection: SchemaInspection) -> bytes:
    """Render an inspection as deterministic UTF-8 Markdown."""

    lines = [
        "# SQLite schema reference",
        "",
        "> Generated by `python -m chess_move_trainer.database schema inspect`; do not edit manually.",
        "",
        "## Database",
        "",
        f"- `user_version`: {inspection.user_version}",
        "",
        "## Object inventory",
        "",
        "| Type | Name | Parent table | Stored SQL |",
        "| --- | --- | --- | --- |",
    ]
    if inspection.objects:
        lines.extend(
            "| {0} | `{1}` | {2} | {3} |".format(
                _cell(item.object_type),
                _cell(item.name),
                _cell(item.table_name),
                "yes" if item.sql is not None else "no",
            )
            for item in inspection.objects
        )
    else:
        lines.append("| *(none)* | | | |")

    lines.extend(["", "## Tables", ""])
    if inspection.tables:
        for table in inspection.tables:
            lines.extend(
                [
                    f"### `{_heading_text(table.name)}`",
                    "",
                    "| Ordinal | Column | Declared type | Nullability | Default | PK order | Kind |",
                    "| ---: | --- | --- | --- | --- | ---: | --- |",
                ]
            )
            if table.columns:
                lines.extend(
                    "| {0} | `{1}` | {2} | {3} | {4} | {5} | {6} |".format(
                        column.ordinal,
                        _cell(column.name),
                        _cell(column.declared_type),
                        "NOT NULL" if column.not_null else "NULLABLE",
                        _cell(column.default_value),
                        column.primary_key_order or "—",
                        _cell(column.kind),
                    )
                    for column in table.columns
                )
            else:
                lines.append("| *(none)* | | | | | | |")

            lines.extend(["", "#### Foreign keys", ""])
            if table.foreign_keys:
                lines.extend(
                    [
                        "| Constraint | Sequence | From | References | To | On update | On delete | Match |",
                        "| ---: | ---: | --- | --- | --- | --- | --- | --- |",
                    ]
                )
                lines.extend(
                    "| {0} | {1} | `{2}` | `{3}` | `{4}` | {5} | {6} | {7} |".format(
                        foreign_key.constraint_id,
                        foreign_key.sequence,
                        _cell(foreign_key.from_column),
                        _cell(foreign_key.referenced_table),
                        _cell(foreign_key.to_column),
                        _cell(foreign_key.on_update),
                        _cell(foreign_key.on_delete),
                        _cell(foreign_key.match),
                    )
                    for foreign_key in table.foreign_keys
                )
            else:
                lines.append("None recorded.")
            lines.append("")
    else:
        lines.append("No tables recorded.")

    lines.extend(
        [
            "## Indexes",
            "",
            "| Name | Table | Unique | Origin | Partial | Columns | Stored SQL |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    if inspection.indexes:
        lines.extend(
            "| `{0}` | `{1}` | {2} | {3} | {4} | {5} | {6} |".format(
                _cell(index.name),
                _cell(index.table_name),
                "yes" if index.unique else "no",
                _cell(index.origin),
                "yes" if index.partial else "no",
                _cell(", ".join(column if column is not None else "<expression>" for column in index.columns)),
                "yes" if index.sql is not None else "no",
            )
            for index in inspection.indexes
        )
    else:
        lines.append("| *(none)* | | | | | | |")

    for object_type, title in (("trigger", "Triggers"), ("view", "Views")):
        lines.extend(["", f"## {title}", ""])
        objects = [item for item in inspection.objects if item.object_type == object_type]
        if objects:
            lines.extend(
                f"- `{_heading_text(item.name)}` on `{_heading_text(item.table_name or '—')}`"
                for item in objects
            )
        else:
            lines.append(f"No {object_type}s recorded.")

    lines.extend(["", "## Stored SQL", ""])
    sql_objects = [item for item in inspection.objects if item.sql is not None]
    if sql_objects:
        for item in sql_objects:
            lines.extend(
                _sql_block(
                    f"{item.object_type} `{item.name}`",
                    item.sql or "",
                )
            )
            lines.append("")
    else:
        lines.append("No stored SQL recorded.")

    return ("\n".join(lines).rstrip("\n") + "\n").encode("utf-8")


def _inspect_connection(connection: Connection) -> SchemaInspection:
    object_rows = connection.exec_driver_sql(
        """
        SELECT type, name, tbl_name, sql
        FROM sqlite_master
        WHERE type IN ('table', 'index', 'trigger', 'view')
        """
    ).all()
    objects = [
        SchemaObject(
            object_type=str(row[0]),
            name=str(row[1]),
            table_name=str(row[2]) if row[2] is not None else None,
            sql=str(row[3]) if row[3] is not None else None,
        )
        for row in object_rows
    ]
    table_sql = {item.name: item.sql for item in objects if item.object_type == "table"}
    table_names = sorted(table_sql, key=_sort_key)

    tables = tuple(
        SchemaTable(
            name=table_name,
            columns=_table_columns(connection, table_name),
            foreign_keys=_foreign_keys(connection, table_name),
            sql=table_sql[table_name],
        )
        for table_name in table_names
    )
    indexes = tuple(
        index
        for table_name in table_names
        for index in _table_indexes(connection, table_name, objects)
    )

    known_index_names = {item.name for item in objects if item.object_type == "index"}
    for index in indexes:
        if index.name not in known_index_names:
            objects.append(
                SchemaObject(
                    object_type="index",
                    name=index.name,
                    table_name=index.table_name,
                    sql=index.sql,
                )
            )

    objects.sort(key=lambda item: (_OBJECT_TYPE_ORDER.get(item.object_type, 99), *_sort_key(item.name)))
    user_version = int(connection.exec_driver_sql("PRAGMA user_version").scalar_one())
    return SchemaInspection(
        user_version=user_version,
        objects=tuple(objects),
        tables=tables,
        indexes=indexes,
    )


def _table_columns(connection: Connection, table_name: str) -> tuple[SchemaColumn, ...]:
    return tuple(
        SchemaColumn(
            ordinal=int(row[0]),
            name=str(row[1]),
            declared_type=str(row[2]) if row[2] is not None else "",
            not_null=bool(row[3]),
            default_value=str(row[4]) if row[4] is not None else None,
            primary_key_order=int(row[5]),
            kind=_column_kind(int(row[6])),
        )
        for row in _pragma_rows(connection, "table_xinfo", table_name)
    )


def _column_kind(xinfo_code: int) -> str:
    return _COLUMN_KIND_BY_XINFO_CODE.get(xinfo_code, f"unknown ({xinfo_code})")


def _foreign_keys(connection: Connection, table_name: str) -> tuple[SchemaForeignKey, ...]:
    foreign_keys = tuple(
        SchemaForeignKey(
            constraint_id=int(row[0]),
            sequence=int(row[1]),
            referenced_table=str(row[2]),
            from_column=str(row[3]),
            to_column=str(row[4]) if row[4] is not None else None,
            on_update=str(row[5]),
            on_delete=str(row[6]),
            match=str(row[7]),
        )
        for row in _pragma_rows(connection, "foreign_key_list", table_name)
    )
    return tuple(sorted(foreign_keys, key=lambda item: (item.constraint_id, item.sequence)))


def _table_indexes(
    connection: Connection,
    table_name: str,
    objects: list[SchemaObject],
) -> tuple[SchemaIndex, ...]:
    sql_by_name = {
        item.name: item.sql
        for item in objects
        if item.object_type == "index" and item.table_name == table_name
    }
    indexes: list[SchemaIndex] = []
    for row in _pragma_rows(connection, "index_list", table_name):
        index_name = str(row[1])
        columns = tuple(
            str(index_row[2]) if index_row[2] is not None else None
            for index_row in _pragma_rows(connection, "index_xinfo", index_name)
            if int(index_row[5]) == 1
        )
        indexes.append(
            SchemaIndex(
                name=index_name,
                table_name=table_name,
                unique=bool(row[2]),
                origin=str(row[3]),
                partial=bool(row[4]),
                columns=columns,
                sql=sql_by_name.get(index_name),
            )
        )
    return tuple(sorted(indexes, key=lambda item: _sort_key(item.name)))


def _pragma_rows(connection: Connection, pragma: str, identifier: str) -> list[tuple[object, ...]]:
    quoted_identifier = '"' + identifier.replace('"', '""') + '"'
    return [tuple(row) for row in connection.exec_driver_sql(f"PRAGMA {pragma}({quoted_identifier})").all()]


def _sort_key(value: str) -> tuple[str, str]:
    return (value.casefold(), value)


def _cell(value: object) -> str:
    if value is None:
        return "—"
    return str(value).replace("\r\n", "\n").replace("\r", "\n").replace("\n", "<br>").replace("|", "\\|")


def _heading_text(value: str) -> str:
    return value.replace("`", "\\`").replace("\n", " ").replace("\r", " ")


def _sql_block(title: str, sql: str) -> list[str]:
    fence = "```"
    while fence in sql:
        fence += "`"
    return [f"### {title}", "", f"{fence}sql", sql.rstrip("\n"), fence]
